### ISSUE TITLE
Able to reproduce Meta's quality? 

### ISSUE THREAD

**Issue by listener17** [NoFish-528/encodec-pytorch#1]
Did you try to replicate training of Meta?
Just curious - if it is at all possible to replicate the stuff from the code that was shared by Meta?

I would be very curious to hear your opinions.

Thanks!

**Comment by ZhikangNiu** [comment]
At the begining, I am a newcomer in speech so I couldn't explained well. And I update some demo, you can listen to those. When training, I'm not add LM model and  use the balancer. But I found the result isn't bad.

**Comment by ZhikangNiu** [comment]
the audio is used our checkpoint which trained in LibriTTS 960h and 16epochs.
When training, I also found the vq loss probably not very important because it didn't converge...
Maybe there are some small bug

**Comment by listener17** [comment]
Thanks for the insights!
