### ISSUE TITLE
Release discriminator checkpoint

### ISSUE THREAD

**Issue by NZqian** [NoFish-528/encodec-pytorch#13]
The pre-trained model on LibriTTS960h works very well, I wonder if you can release the corresponding discriminator checkpoint so I can continue training on my custom dataset instead of training from scrach.

**Comment by ZhikangNiu** [comment]
> The pre-trained model on LibriTTS960h works very well, I wonder if you can release the corresponding discriminator checkpoint so I can continue training on my custom dataset instead of training from scrach.

Thanks for your attention, I have uploaded the disc checkpoint on huggingface just now. @NZqian 
And if you have any other question about train encodec, please contact me by using email or wechat
email: zkniu@stu.xidian.edu.cn 
wechat: ZhikangNiu_Wechat
