### ISSUE TITLE
is there any sample ?

### ISSUE THREAD

**Issue by choiHkk** [NoFish-528/encodec-pytorch#14]
thank you for your hard work.
i would like to customize and use this code, but before that, I'd like to try out a test sample.
could I listen to a test sample from the model you trained?

**Comment by ZhikangNiu** [comment]
> thank you for your hard work.
> i would like to customize and use this code, but before that, I'd like to try out a test sample.
> could I listen to a test sample from the model you trained?

Thank you for your attention. You can use our hugging face model and main.py to generate more test samples.

**Comment by ZhikangNiu** [comment]
all checkpoints have released

**Comment by choiHkk** [comment]
i'm sorry, i just confirmed the presence of a pre-trained model.
thank you once again for your efforts.

**Comment by ZhikangNiu** [comment]
> i'm sorry, i just confirmed the presence of a pre-trained model.
> thank you once again for your efforts.

it doesn't matter. Hope this code can help you.
