### ISSUE TITLE
[REQ] add license file

### ISSUE THREAD

**Issue by MarcoRavich** [NoFish-528/encodec-pytorch#16]
Hi there, 1st of all thanks for your awesome work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [AUDIO](https://github.com/forart/HyMPS#-) \ [AI-based projects page](https://github.com/forart/HyMPS/blob/main/AIaudio.md#--) \ [Codecs subsection](https://github.com/forart/HyMPS/blob/main/AIaudio.md#codecs-)), can you please add a "GH-standardized" license file ?

Expliciting licensing terms is extremely important to let other devs (and not only) understand how to reuse/adapt/modify your code in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/NoFish-528/encodec-pytorch/?label=LICENSE)
(generative URL: https://flat.badgen.net/github/license/NoFish-528/encodec-pytorch/?label=LICENSE)

Anyway you can easily set a "compliant" one through the GH's license wizard tool.

Last but not least, let us know how - in your opinion - we could improve categorization/sorting of collected projects in order to push their evolution by favouring collaborations between developers (and not only).

Thanks in advance.

**Comment by ZhikangNiu** [comment]
add LICENSE
