### ISSUE TITLE
traing convergence

### ISSUE THREAD

**Issue by yangyyt** [NoFish-528/encodec-pytorch#25]
The effect of multi-gpus training is not as good as that of single-card training, and it feels that multi-card training is quickly overfitted.

**Comment by ZhikangNiu** [comment]
Maybe every gpu's codebook weight different?
you can try this code?
https://github.com/ZhikangNiu/encodec-pytorch/blob/c6b6de91c4bfeb8582b5e51f1a8b599e04b7d860/quantization/core_vq.py#L157
