### ISSUE TITLE
Training speed

### ISSUE THREAD

**Issue by zhangchi2004** [NoFish-528/encodec-pytorch#27]
I am training encodec on 8 gpus. The current training speed of the model is exceptionally slow, about 10min per 100 iterations. I don't know whether the gpus are fully utilized. Could you please give a reference for a normal training speed? Meanwhile, do you know which part of the model could be the bottleneck for training speed?

**Comment by zhangchi2004** [comment]
It seems in my case that the training speed highly correlates to batch size. It cost 50, 75, 136 seconds for 100 iterations when batch size are 1,2,4 respectively. When the batch_size is grown to 64 it slows down to 600s/100iters. Do you know what might cause this?

**Comment by ZhikangNiu** [comment]
> It seems in my case that the training speed highly correlates to batch size. It cost 50, 75, 136 seconds for 100 iterations when batch size are 1,2,4 respectively. When the batch_size is grown to 64 it slows down to 600s/100iters. Do you know what might cause this?

I think my customAudioDataset is too naive to slow. If you have wechat, you can add me wechat: 18628618289

**Comment by ZhikangNiu** [comment]
I will close this issue, if you have any questions you can re-open it. feel free to ask question
