### ISSUE TITLE
你的模型可不可以导入官方的模型参数进行微调呀？

### ISSUE THREAD

**Issue by zhaojingxin123** [NoFish-528/encodec-pytorch#28]
你的模型可不可以导入官方的模型参数进行微调呀？

**Comment by ZhikangNiu** [comment]
我尚未尝试过 但理论上应该是可以的发自我的 iPhone在 2024年7月17日，23:26，zhaojingxin123 ***@***.***> 写道：﻿
你的模型可不可以导入官方的模型参数进行微调呀？

**Comment by ZhikangNiu** [comment]
I will close this issue, if you have any questions you can re-open it. feel free to ask question
