### ISSUE TITLE
encodec_ASR

### ISSUE THREAD

**Issue by coding-sharks** [NoFish-528/encodec-pytorch#29]
hi~i have one question about encodec, I have noticed some research focus on TTS using encodec. So how about ASR using encodec? I wonder if you have tried it!

**Comment by ZhikangNiu** [comment]
> hi~i have one question about encodec, I have noticed some research focus on TTS using encodec. So how about ASR using encodec? I wonder if you have tried it!

I have not tried encodec in ASR, but you can read https://arxiv.org/abs/2309.07377

**Comment by coding-sharks** [comment]
> > hi~i have one question about encodec, I have noticed some research focus on TTS using encodec. So how about ASR using encodec? I wonder if you have tried it!
> 
> I have not tried encodec in ASR, but you can read https://arxiv.org/abs/2309.07377

Many Thanks! I will quote this paper.
