### ISSUE TITLE
Muti GPU train_discriminator has some confused

### ISSUE THREAD

**Issue by QingliangMeng** [NoFish-528/encodec-pytorch#30]
When I train on multiple GPUs, start training the discriminator, the following error occurs：

RuntimeError: Detected mismatch between collectives on ranks. Rank 0 is running collective: CollectiveFingerPrint(OpType=BROADCAST, TensorShape=[], TensorDtypes=Long, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cuda, layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt))), but Rank 1 is running collective: CollectiveFingerPrint(OpType=ALLGATHER_COALESCED).

I found that this condition may have different results on different ranks.

train_discriminator = (config.model.train_discriminator
                               and epoch >= config.lr_scheduler.warmup_epoch
                               and random.random() < float(config.model.train_discriminator))
if train_discriminator:

I speculate that because the train_discriminator in different rank of the appeal will cause the following error or index out of bounds. There are comments where there are errors：

bw = self.target_bandwidths[index.item()]# fixme: variable bandwidth training, if you broadcast bd, the broadcast will encounter error

So I set train_discriminator to True forever, and the error disappeared, I would like to ask if this situation has ever happened to the author, and does this flag have any special meaning?

**Comment by ZhikangNiu** [comment]
> When I train on multiple GPUs, start training the discriminator, the following error occurs：
> 
> RuntimeError: Detected mismatch between collectives on ranks. Rank 0 is running collective: CollectiveFingerPrint(OpType=BROADCAST, TensorShape=[], TensorDtypes=Long, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cuda, layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt))), but Rank 1 is running collective: CollectiveFingerPrint(OpType=ALLGATHER_COALESCED).
> 
> I found that this condition may have different results on different ranks.
> 
> train_discriminator = (config.model.train_discriminator and epoch >= config.lr_scheduler.warmup_epoch and random.random() < float(config.model.train_discriminator)) if train_discriminator:
> 
> I speculate that because the train_discriminator in different rank of the appeal will cause the following error or index out of bounds. There are comments where there are errors：
> 
> bw = self.target_bandwidths[index.item()]# fixme: variable bandwidth training, if you broadcast bd, the broadcast will encounter error
> 
> So I set train_discriminator to True forever, and the error disappeared, I would like to ask if this situation has ever happened to the author, and does this flag have any special meaning?


https://github.com/ZhikangNiu/encodec-pytorch/blob/c6b6de91c4bfeb8582b5e51f1a8b599e04b7d860/train_multi_gpu.py#L107

yeah, you're right. When we use multi gpu, every gpu could have different random.random(). It will show this error. train_discriminator=True, it means 1 step update generator, 1 step update discriminator. We can set it's a probability, to make it update 2 step generator, 1 step discriminator. You can add a new pull request if you want and I will merge it. We can fix this problem with broadcast random.random() from GPU:0 to others? Please check this question @leoauri

**Comment by ZhikangNiu** [comment]
> > When I train on multiple GPUs, start training the discriminator, the following error occurs：
> > RuntimeError: Detected mismatch between collectives on ranks. Rank 0 is running collective: CollectiveFingerPrint(OpType=BROADCAST, TensorShape=[], TensorDtypes=Long, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cuda, layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt))), but Rank 1 is running collective: CollectiveFingerPrint(OpType=ALLGATHER_COALESCED).
> > I found that this condition may have different results on different ranks.
> > train_discriminator = (config.model.train_discriminator and epoch >= config.lr_scheduler.warmup_epoch and random.random() < float(config.model.train_discriminator)) if train_discriminator:
> > I speculate that because the train_discriminator in different rank of the appeal will cause the following error or index out of bounds. There are comments where there are errors：
> > bw = self.target_bandwidths[index.item()]# fixme: variable bandwidth training, if you broadcast bd, the broadcast will encounter error
> > So I set train_discriminator to True forever, and the error disappeared, I would like to ask if this situation has ever happened to the author, and does this flag have any special meaning?
> 
> https://github.com/ZhikangNiu/encodec-pytorch/blob/c6b6de91c4bfeb8582b5e51f1a8b599e04b7d860/train_multi_gpu.py#L107
> 
> yeah, you're right. When we use multi gpu, every gpu could have different random.random(). It will show this error. train_discriminator=True, it means 1 step update generator, 1 step update discriminator. We can set it's a probability, to make it update 2 step generator, 1 step discriminator. You can add a new pull request if you want and I will merge it. We can fix this problem with broadcast random.random() from GPU:0 to others? Please check this question @leoauri

Maybe the following code can solve?
```python
def get_train_discriminator():
    local_train_discriminator = (config.model.train_discriminator 
                                  and epoch >= config.lr_scheduler.warmup_epoch 
                                  and random.random() < float(config.model.train_discriminator))
    
    # broadcast from cuda:0 to other cuda
    if dist.get_rank() == 0:
        # cuda:0 上的 local_train_discriminator
        local_train_discriminator_tensor = torch.tensor(int(local_train_discriminator), dtype=torch.int32).cuda()
    else:
        local_train_discriminator_tensor = torch.empty(1, dtype=torch.int32).cuda()
    
    dist.broadcast(local_train_discriminator_tensor, src=0)
    
    global_train_discriminator = local_train_discriminator_tensor.item() > 0
    return global_train_discriminator

train_discriminator = get_train_discriminator()
```

**Comment by ZhikangNiu** [comment]
@QingliangMeng @leoauri

**Comment by QingliangMeng** [comment]
Thank you very much for your reply! ~ I think I know why it is designed that way. I will try it myself.

**Comment by ZhikangNiu** [comment]
> Thank you very much for your reply! ~ I think I know why it is designed that way. I will try it myself.

yeah, if available, i hope you can check this solution code and make a new pull request to fix this? 🥇
