### ISSUE TITLE
48 kHz mono training?

### ISSUE THREAD

**Issue by listener17** [NoFish-528/encodec-pytorch#4]
Hi! I think the code works mechanically to train the 24 kHz model. Do you know if one can train 48 kHz mono?

**Comment by ZhikangNiu** [comment]
yes，I only need to train 24khz encodec，but I think the 48khz encodec training you only change some details follow the original paper

**Comment by ZhikangNiu** [comment]
I will test the 48khz encodec training when I'm available

**Comment by ZhikangNiu** [comment]
If you add the 48khz training, I think you can make a pull request?
